# Generated by Django 2.0 on 2021-07-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('books_count', models.IntegerField()),
                ('isbn', models.TextField()),
                ('authors', models.TextField()),
                ('original_publication_year', models.TextField()),
                ('original_title', models.TextField()),
                ('average_rating', models.FloatField()),
                ('image_url', models.TextField()),
                ('small_image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.TextField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
            ],
        ),
    ]
