# Generated by Django 2.0 on 2021-07-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='books_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_publication_year',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='small_image_url',
            field=models.TextField(null=True),
        ),
    ]
