# Generated by Django 2.0 on 2021-07-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20210716_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='books_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_publication_year',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='small_image_url',
            field=models.TextField(default=''),
        ),
    ]
