# Generated by Django 2.0 on 2021-07-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20210716_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='original_title',
            new_name='title',
        ),
    ]
