# Generated by Django 2.0 on 2021-07-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20210716_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
