# Generated by Django 2.0 on 2021-07-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_auto_20210716_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_publication_year',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='book',
            name='small_image_url',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
