# Generated by Django 2.0 on 2021-07-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0010_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodreads_book_id', models.IntegerField()),
                ('genre', models.TextField()),
            ],
        ),
    ]
